SELECT
    S.sbs_no AS SBS_NO,
    D.Dcs_Code AS Dcs_Code,
    (D.D_Name || ' ' || D.C_Name || ' ' || D.S_Name) AS Dcs_Name,
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM VOU.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN VOU.VOUCOST END), 2), 0) AS "RCVD COST LAST YEAR",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM VOU.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN VOU.VOUPRICE END), 2), 0) AS "RCVD PRICE LAST YEAR",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM SAL.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN SAL.SALCOST END), 2), 0) AS "SOLD COST LAST YEAR",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM SAL.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) - 1 THEN SAL.SALPRICE END), 2), 0) AS "SOLD PRICE LAST YEAR",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM VOU.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) THEN VOU.VOUCOST END), 2), 0) AS "RCVD COST YTD",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM VOU.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) THEN VOU.VOUPRICE END), 2), 0) AS "RCVD PRICE YTD",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM SAL.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) THEN SAL.SALCOST END), 2), 0) AS "SOLD COST YTD",
    COALESCE(ROUND(SUM(CASE WHEN EXTRACT(YEAR FROM SAL.invc_post_date) = EXTRACT(YEAR FROM SYSDATE) THEN SAL.SALPRICE END), 2), 0) AS "SOLD PRICE YTD",
    COALESCE(ROUND(AVG(OH.INVCOST), 2), 0) AS "ON HAND COST",
    COALESCE(ROUND(AVG(OH.INVPRICE), 2), 0) AS "ON HAND PRICE"
FROM
    Rps.Dcs D
    INNER JOIN Rps.Subsidiary S ON S.Sid = D.Sbs_Sid
    INNER JOIN Rps.Invn_Sbs_Item I ON S.Sid = I.Sbs_Sid AND D.Sid = I.Dcs_Sid
LEFT JOIN
(Select S.Sbs_NO, D.Dcs_CODE, Coalesce(Round(Sum(Qty * Cost),2),0) Invcost, Coalesce(Round(Sum(Qty * Price),2),0) Invprice
From RPS.Invn_Sbs_Item Inv
Join Rps.Invn_Sbs_Item_Qty Iq On Inv.Sid=Iq.Invn_Sbs_Item_Sid And Inv.Sbs_Sid=Iq.Sbs_Sid
Left Join Rps.Invn_Sbs_Price Isp On Inv.Sid=Isp.Invn_Sbs_Item_Sid And Inv.Sbs_Sid=Isp.Sbs_Sid
left JOIN RPS.price_level pl ON isp.price_lvl_sid = pl.sid
LEFT JOIN RPS.DCS D ON INV.DCS_SID=D.SID 
LEFT JOIN RPS.SUBSIDIARY S ON S.SID=INV.SBS_SID
WHERE PL.price_lvl=1 
group by S.sbs_NO, D.dcs_CODE) OH
ON S.SBS_NO=OH.SBS_NO AND OH.DCS_CODE=D.DCS_CODE
LEFT JOIN
(SELECT A.SBS_NO,A.invc_post_date, B.DCS_CODE,
SUM((CASE WHEN B.ITEM_TYPE=2 THEN B.QTY*-1 ELSE B.QTY END)* COST) SALCOST,
SUM((CASE WHEN B.ITEM_TYPE=2 THEN B.QTY*-1 ELSE B.QTY END)* B.PRICE) SALPRICE
FROM RPS.DOCUMENT A,RPS.DOCUMENT_ITEM B,RPS.SUBSIDIARY S
WHERE A.SID=B.DOC_SID AND A.IS_HELD=0 AND A.RECEIPT_TYPE IN (0,1) AND A.STATUS=4
AND B.ITEM_TYPE IN (1,2) AND A.SBS_NO=S.SBS_NO 
GROUP BY A.SBS_NO,A.invc_post_date, B.DCS_CODE
) SAL
ON S.SBS_NO=SAL.SBS_NO AND SAL.DCS_CODE=D.DCS_CODE
LEFT JOIN
(SELECT S.SBS_NO,A.invc_post_date, D.DCS_CODE,
SUM((CASE WHEN A.VOU_TYPE=1 THEN B.QTY*-1 ELSE B.QTY END)* B.COST) VOUCOST,
SUM((CASE WHEN A.VOU_TYPE=1 THEN B.QTY*-1 ELSE B.QTY END)* B.PRICE) VOUPRICE
FROM RPS.VOUCHER A,RPS.VOU_ITEM B,RPS.SUBSIDIARY S,RPS.DCS D, RPS.INVN_SBS_ITEM I
WHERE A.SID=B.VOU_SID 
AND A.VOU_TYPE IN (0,1) AND I.SID=B.ITEM_SID AND I.DCS_SID=D.SID
AND A.VOU_CLASS=0 AND A.SLIP_FLAG=0 AND A.HELD=0 AND A.STATUS=4
AND A.SBS_SID=S.SID 
GROUP BY S.SBS_NO,A.invc_post_date, D.DCS_CODE
) VOU
ON S.SBS_NO=VOU.SBS_NO AND VOU.DCS_CODE=D.DCS_CODE
Group By
    S.Sbs_No, D.Dcs_Code, D.D_Name, D.C_Name, D.S_Name
ORDER BY
    S.Sbs_No, D.Dcs_Code